### ISSUE TITLE
ITUNE

### ISSUE THREAD

**Issue by PANOSPAP1982** [RYSKZ/SongCat#1]
HELLO FROM GREECE!!!PLEASEEEEEEEE RYSKZ CAN YOU RELEASE IT?PLEASE MANNNNNNNNNNN

**Comment by RYSKZ** [comment]
Dude, you again, it's already released, just follow the instructions indicated in the README.

You just need Python installed, nothing more.

**Comment by PANOSPAP1982** [comment]
my frienddddddddd unfortunately I have no idea how to do it!!!please can we use teamviewer to do it for me?I AM BEGGING YOU MAN

**Comment by RYSKZ** [comment]
I think the instructions are clear enough, I recommend you to rather spend the time in learning the basics of software installation and usage than wasting your time.

**Comment by PANOSPAP1982** [comment]
BUT RYSZ I HAVE NO IDEA FROM DEVELOPING AND PROGRAMMING!!!!THATS WHY I NEED YOUR HELP MY GOOD FRIEND!!!

**Comment by RYSKZ** [comment]
You don't need to program anything, this is already finished and working.

**Comment by PANOSPAP1982** [comment]
PLEASE CAN YOU HELP ME STEP BY STEP?WHAT I HAVE TO DO?

**Comment by RYSKZ** [comment]
Download and install Python 2.7 (search in Google)
Restart your PC
Follow this: https://github.com/RYSKZ/SongCat#use

**Comment by PANOSPAP1982** [comment]
WOOW...OKKKK....I HAVE RESTART FIRST?

**Comment by RYSKZ** [comment]
Once you have installed Python

**Comment by PANOSPAP1982** [comment]
AAA OK!!!MY FRIEND THIS IS FOR SEARCHING MUSIC SONGS AND ALBUMS FROM ITUNES...RIGHT?

**Comment by RYSKZ** [comment]
No, this is for music tagging, for searching use this: https://github.com/RYSKZ/iTunes-Song-Search/

**Comment by RYSKZ** [comment]
Download and extract: https://github.com/RYSKZ/iTunes-Song-Search/archive/master.zip

**Comment by PANOSPAP1982** [comment]
READY MY FRIEND!!!I HAVE EXTRACT IT ALREADY!!!AND NOW?

**Comment by RYSKZ** [comment]
Did you installed python 2.7 and restarted?

**Comment by PANOSPAP1982** [comment]
AAAA I NEED ALSO ?BECAUSE I THINK FOR SEARCHING MUSIC I DONT NEED IT!!!BUT OK.THIS IS THE CORRECT? python-2.7.amd64

**Comment by RYSKZ** [comment]
https://www.python.org/ftp/python/2.7.16/python-2.7.16.amd64.msi

**Comment by PANOSPAP1982** [comment]
THANKS FOR THE LINK MY FRIEND!!!I HAVE INSTALL IT

**Comment by PANOSPAP1982** [comment]
NOW I MUST RESTART?

**Comment by PANOSPAP1982** [comment]
ready!!! I restart my pc!!!now my friend?

**Comment by PANOSPAP1982** [comment]
woooooooooo how can I use these my frienddddddddd???? 

35 lines (31 sloc)  1.16 KB
  
You're using code navigation to jump to definitions or references.
Learn more or give us feedback
import itunes
import sys

track = itunes.search_song(" ".join(sys.argv[1:]))[0]
album = track.get_album()

title = track.get_name()
album_title = album.get_name()
artists = track.get_artist().get_name()
release_date = track.get_release_date()
track_number = track.get_disc_number()
total_tracks = album.get_track_count()
genre = track.get_genre()
album_artist = album.get_artist().get_name()
disc_number = track.get_disc_number()
total_discs = 1
duration = track.get_duration()
minutes = int(duration / 60)
seconds = int(duration / 60 % 1 * 100)

print "Title: " + title
print "Album: " + album_title
print "Artists: " + artists
print "Release Date: " + release_date 
print "Track number: " + str(track_number) + "/" + str(total_tracks)
print "Genre: " + genre
print "Album Artist: " + album_artist
print "Disc Number: " + str(disc_number) + "/" + str(total_discs)
print "Duration: " + str(minutes) + "m " + str(seconds) + "s"

**Comment by RYSKZ** [comment]
open a cmd (find on google)
type python search.py

**Comment by PANOSPAP1982** [comment]
on google what  I have to search>?

**Comment by PANOSPAP1982** [comment]
Filename, size | File type | Python version | Upload date | Hashes
-- | -- | -- | -- | --
Wheel | py2.py3 | Apr 10, 2019 | View
Source | None | Apr 10, 2019

wich one?

**Comment by PANOSPAP1982** [comment]
my friend???
